/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To analyze key business measures across major dimensions.
    - To understand customer distribution, product variety, revenue, and sales
      behavior across regions and user segments.

Concepts Used:
    - COUNT(), SUM(), AVG()
    - GROUP BY, ORDER BY
    - LEFT JOIN for combining fact + dimension tables
===============================================================================
*/


---------------------------------------------
-- Total customers by country
---------------------------------------------
SELECT 
    country,
    COUNT(DISTINCT customer_id) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;


---------------------------------------------
-- Total customers by gender
---------------------------------------------
SELECT 
    gender,
    COUNT(DISTINCT customer_id) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;


---------------------------------------------
-- Total products by category
---------------------------------------------
SELECT
    category,
    COUNT(product_id) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;


---------------------------------------------
-- Average cost for each product category
---------------------------------------------
SELECT
    category,
    AVG(cost) AS avg_costs
FROM gold.dim_products
GROUP BY category
ORDER BY avg_costs DESC;


---------------------------------------------
-- Total revenue generated for each category
---------------------------------------------
SELECT
    p.category,
    SUM(fs.sales_amount) AS total_revenue
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_products AS p
    ON p.product_key = fs.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;


---------------------------------------------
-- Total revenue generated by each customer
---------------------------------------------
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(fs.sales_amount) AS total_revenue
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_customers AS c
    ON c.customer_key = fs.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;


---------------------------------------------
-- Distribution of sold items across countries
---------------------------------------------
SELECT 
    c.country,
    SUM(fs.quantity) AS total_quantity_by_country
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_customers AS c
    ON c.customer_key = fs.customer_key
GROUP BY c.country
ORDER BY total_quantity_by_country DESC;
